language: ruby

rvm:
  - 2.4.1

os:
  - linux
  - osx

sudo: false

gemfile:
  - Gemfile

matrix:
  allow_failures:
    - rvm: 2.3.0
      os: osx
    - rvm: ruby-head
    - rvm: jruby-head
    - rvm: jruby-19mode
      os: osx
    - rvm: jruby-9.0.5.0
      os: osx
    - rvm: rbx-2
